export const productsData = [
    {
        id: 1,
        image: "https://www.volkswagenparca.net/wp-content/uploads/balata.jpg",
        partNo: "61324214",
        partName: "Balata",
        brand: "BMW",
        model: "A6",
        price: 125,
    },
    {
        id: 2,
        image: "https://x-tremetuning.com/images/detailed/15/susturucu-4.png",
        partNo: "24324241",
        partName: "Egzoz",
        brand: "Mercedes",
        model: "Benz",
        price: 125,
    },
    {
        id: 3,
        image: "https://e7.pngegg.com/pngimages/254/207/png-clipart-car-engine-car-car-engine.png",
        partNo: "421313214",
        partName: "Motor",
        brand: "Fiat",
        model: "Fiorino",
        price: 125,
    },
    {
        id: 4,
        image: "https://u.preparegood.news/img/products/27863-evrensel-u-tipi-yumusak-cercevesiz-bracketless-araba-oen-cam-silecegi-bcak-kaucuk-araba-ds-aksesuarlar-14-393916-3939-21-223939-243939.jpg",
        partNo: "4324324",
        partName: "Silicek",
        brand: "Hyundai",
        model: "Civic",
        price: 125,
    },
    {
        id: 5,
        image: "http://res.cloudinary.com/tasit-com/image/upload/c_scale,w_600/v1490280022/buji_zqlrug.jpg",
        partNo: "2131234",
        partName: "Buji",
        brand: "Renault",
        model: "Megane",
        price: 455,
    },
];